sudo: false
language: scala
jdk:
- oraclejdk8
scala:
- 2.11.12
- 2.12.8
- 2.13.0
script:
   - sbt ++$TRAVIS_SCALA_VERSION test
   - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt updateImpactSubmit || true'
